name: Publish Package to npmjs
on:
  release:
    types: [published]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - name: check versions
        run: |
          node --version
          npm --version

      - run: npm clean-install

      - run: npm run build

      - run: npm publish --access public
